#!/usr/bin/env python3
"""
Generate a polished CoDeC comparison figure from comparison.csv.
"""
import argparse
import matplotlib
matplotlib.use("Agg")  # Non-interactive backend to avoid segfault
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

# Refined palette - teal/amber for seen/unseen, emerald/rose for AUC
COLOR_SEEN = "#0d9488"    # teal
COLOR_UNSEEN = "#d97706"  # amber
COLOR_AUC_GOOD = "#059669"  # emerald
COLOR_AUC_BAD = "#b91c1c"  # rose
COLOR_BG = "#fafaf9"      # warm white
COLOR_GRID = "#e7e5e4"


def _display_model_name(name: str) -> str:
    s = str(name or "")
    if s.startswith("vllm:"):
        s = s[len("vllm:"):]
    if "/" in s:
        s = s.split("/")[-1]
    s = s.replace("Meta-Llama-3.1-405B-Instruct", "Llama-3.1-405b-instruct")
    s = s.replace("Llama-3.1-405B-Instruct-NVFP4", "Llama-3.1-405b-instruct-NVFP4")
    return s


def main():
    parser = argparse.ArgumentParser(description="Plot CoDeC comparison figure from CSV")
    parser.add_argument("--csv", default="comparison.csv", help="Input CSV path (default: comparison.csv)")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"Error: {csv_path} not found. Run compare_codec_results.py first.")
        return

    # Load data from the CSV generated by compare_codec_results.py
    df = pd.read_csv(csv_path)
    
    # Process model names for display
    df["Display Model"] = df["Model"].apply(_display_model_name)
    
    # Fill NAs with 0 for plotting
    df = df.fillna(0)

    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Helvetica", "DejaVu Sans", "Arial"],
        "axes.facecolor": COLOR_BG,
        "figure.facecolor": "white",
    })

    fig, ax1 = plt.subplots(1, 1, figsize=(8.5, 5.5))
    fig.patch.set_facecolor("white")

    models = df["Display Model"].tolist()
    seen = df["Seen mean (%)"].tolist()
    unseen = df["Unseen mean (%)"].tolist()
    aucs = df["AUC (%)"].tolist()
    x = np.arange(len(models))
    width = 0.36
    base_dir = Path(__file__).parent

    # --- Figure 1: Seen vs Unseen Contamination Scores ---
    fig1, ax1 = plt.subplots(1, 1, figsize=(8.5, 5.5))
    fig1.patch.set_facecolor("white")
    ax1.set_facecolor(COLOR_BG)
    bars1 = ax1.bar(x - width/2, seen, width, label="Seen", color=COLOR_SEEN, alpha=0.92, edgecolor="white", linewidth=1.2)
    bars2 = ax1.bar(x + width/2, unseen, width, label="Unseen", color=COLOR_UNSEEN, alpha=0.92, edgecolor="white", linewidth=1.2)
    for i, model in enumerate(models):
        if "gemini" in model.lower():
            bars1[i].set_alpha(0.45)
            bars1[i].set_hatch("//")
            bars2[i].set_alpha(0.45)
            bars2[i].set_hatch("//")
    ax1.set_ylabel("CoDeC Score (%)", fontsize=12, fontweight="600", color="#374151")
    ax1.set_title("Seen vs Unseen Contamination Scores", fontsize=13, fontweight="600", color="#1f2937", pad=12)
    ax1.set_xticks(x)
    ax1.set_xticklabels(models, fontsize=10, fontweight="500", rotation=15, ha="right")
    ax1.legend(loc="upper right", framealpha=0.98, fontsize=10, edgecolor=COLOR_GRID)
    ax1.set_ylim(0, 100)
    ax1.set_xlim(-0.6, len(models) - 0.4)
    ax1.yaxis.grid(True, linestyle="-", alpha=0.4, color=COLOR_GRID)
    ax1.set_axisbelow(True)
    for spine in ["top", "right"]:
        ax1.spines[spine].set_visible(False)
    if any("gemini" in m.lower() for m in models):
        fig1.text(0.5, 0.01, "Note: Gemini scores are invalid (API returns logprobs only for generated tokens, not prompt tokens).",
                  ha="center", fontsize=9, style="italic", color="#6b7280", wrap=True)
    plt.tight_layout(rect=[0, 0.04, 1, 1])
    fig1.savefig(base_dir / "codec_contamination_scores.pdf", dpi=200, bbox_inches="tight", facecolor="white", edgecolor="none")
    fig1.savefig(base_dir / "codec_contamination_scores.png", dpi=200, bbox_inches="tight", facecolor="white", edgecolor="none")
    plt.close(fig1)
    print(f"Saved {base_dir / 'codec_contamination_scores.pdf'}")
    print(f"Saved {base_dir / 'codec_contamination_scores.png'}")

    # --- Figure 2: Classification AUC (Seen vs Unseen) ---
    fig2, ax2 = plt.subplots(1, 1, figsize=(8.5, 5.5))
    fig2.patch.set_facecolor("white")
    ax2.set_facecolor(COLOR_BG)
    colors_auc = [COLOR_AUC_GOOD if a >= 90 else COLOR_AUC_BAD for a in aucs]
    bars_auc = ax2.bar(x, aucs, width=0.6, color=colors_auc, alpha=0.92, edgecolor="white", linewidth=1.2)
    for i, model in enumerate(models):
        if "gemini" in model.lower():
            bars_auc[i].set_alpha(0.45)
            bars_auc[i].set_hatch("//")
    ax2.set_ylabel("AUC (%)", fontsize=12, fontweight="600", color="#374151")
    ax2.set_title("Classification AUC (Seen vs Unseen)", fontsize=13, fontweight="600", color="#1f2937", pad=12)
    ax2.set_xticks(x)
    ax2.set_xticklabels(models, fontsize=10, fontweight="500", rotation=15, ha="right")
    ax2.axhline(y=50, color="#9ca3af", linestyle="--", alpha=0.6, linewidth=1)
    ax2.set_ylim(0, 110)
    ax2.set_xlim(-0.5, len(models) - 0.5)
    ax2.yaxis.grid(True, linestyle="-", alpha=0.4, color=COLOR_GRID)
    ax2.set_axisbelow(True)
    for spine in ["top", "right"]:
        ax2.spines[spine].set_visible(False)
    for v, bar in zip(aucs, bars_auc):
        if v > 0:
            ax2.text(bar.get_x() + bar.get_width()/2, v + 4, f"{v:.1f}%", ha="center", fontsize=10, fontweight="600", color="#374151")
    plt.tight_layout(rect=[0, 0.04, 1, 1])
    fig2.savefig(base_dir / "codec_auc.pdf", dpi=200, bbox_inches="tight", facecolor="white", edgecolor="none")
    fig2.savefig(base_dir / "codec_auc.png", dpi=200, bbox_inches="tight", facecolor="white", edgecolor="none")
    plt.close(fig2)
    print(f"Saved {base_dir / 'codec_auc.pdf'}")
    print(f"Saved {base_dir / 'codec_auc.png'}")

if __name__ == "__main__":
    main()
